sudo: false
language: php

env:
  TRAVIS_BUILD=true

php:
  - 5.4
  - 5.5
  - 5.6


before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit -v -c phpunit.xml